### ISSUE TITLE
Not all stations directly playable

### ISSUE THREAD

**Issue by numberoverzero** [numberoverzero/brainfm#1]
Some stations require a duration selection, which is where `getStationsByID` comes in.

I think the right property to look at is either `"enable_time_options"` or `"player"`

**Comment by numberoverzero** [comment]
Here's a focus station:

```
{
    "active": 1,
    "alias_station_id": 0,
    "classes": "station_bg_orange",
    "display_order": 0,
    "duration_override": 0,
    "enable_chaining": 0,
--->"enable_time_options": 1,
    "for_home_screen": 0,
    "for_trial": 1,
    "header_text": null,
    "id": 300,
    "image": "/images/icons/sessions/explore/cinematic.png",
    "length": 30,
    "name": "Cinematic Music Focus",
    "parent_id": 48,
    "path_column": "path",
--->"player": 1,
    "quote_group_id": 14,
    "randomly_assign": 0,
    "requires_intro": 0,
    "schedule_category_id": 1,
    "string_id": "explore.focus.cinematic",
    "subgroup_title": null,
    "theme": "teal",
    "timestamp": "2016-10-18T00:14:36.000Z",
    "toplevel_parent_id": 46,
    "unlocked_for_trial": 1,
    "use_example": null
}
```

and here's a sleep station:

```
{
    "active": 1,
    "alias_station_id": 0,
    "classes": "station_bg_greenyellow",
    "display_order": 0,
    "duration_override": 0,
    "enable_chaining": 0,
--->"enable_time_options": 0,
    "for_home_screen": 0,
    "for_trial": 1,
    "header_text": "How long would you like to sleep?",
    "id": 71,
    "image": "/images/icons/sessions/explore/music.png",
    "length": 0,
    "name": "Ambient Music Sleep",
    "parent_id": 49,
    "path_column": "path",
--->"player": 0,
    "quote_group_id": 1,
    "randomly_assign": 1,
    "requires_intro": 0,
    "schedule_category_id": 3,
    "string_id": "explore.sleep.ambient",
    "subgroup_title": null,
    "theme": "bluegreen",
    "timestamp": "2015-11-03T10:52:17.000Z",
    "toplevel_parent_id": 46,
    "unlocked_for_trial": null,
    "use_example": null
}
```

**Comment by numberoverzero** [comment]
Also, it looks like they can nest arbitrarily.  Not sure yet what the marker is, but for example:

`71 -> 194 -> 88`

**Comment by williamhatcher** [comment]
Bump. Update please?

**Comment by numberoverzero** [comment]
Thanks for the comment.  I actually hit this last night trying to play a sleep station, having forgotten that it doesn't work.  That was disappointing.

This issue has been low priority since I mostly listen to focus stations at work, and the API requires a lot of trial and error to actually find what we're looking for (there's not an official API).  Contributions are certainly welcome; either suggestions for how you'd like this library to specify the duration parameter, or debugging wire calls so we can rebuild the calls more quickly.

If not though, this will probably get annoying enough to cross some activation threshold for me in the near future.

**Comment by numberoverzero** [comment]
Given the upcoming api changes, I'm going to close this.  `brain ls` will now call `GET /stations` which contains all details; there's no need to walk parent/child branches.

Since I haven't published to pypi yet, you can install the latest dev branch with:

```
pip install git+git://github.com/numberoverzero/brainfm.git@feature/v2-api-fix
```
