### ISSUE TITLE
404 error on start

### ISSUE THREAD

**Issue by zmre** [numberoverzero/brainfm#11]
I was excited to try this out and get brain.fm out of a browser tab. Alas, when I try to run the script, I get this error:

    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.brain.fm/post/rtecmg

I assume the brain.fm folks have changed something. Any hope of getting an update to the CLI?

**Comment by zmre** [comment]
I should note this happens when I use `brain ls` from the CLI.  I've put config info into `~/.brainfm/config`.  When I launch a python interactive session and use the function to `get_stations()` from there, it works fine.

**Comment by numberoverzero** [comment]
Thanks very much for opening an issue, and sorry to hear this isn't working for you.

From your last comment this doesn't sound like the website changed.  If it had, get_stations() should fail from everywhere since the cli is just a wrapper around that.

I tested locally to see if that was still working, and it looks ok:

```
$ brain ls
+Available Stations------------+---------------------------+
| id  | name                   | canonical                 |
+-----+------------------------+---------------------------+
| 34  | Relaxed Focus          | explore.relaxed           |
| 53  | Beach Focus            | explore.focus.beach       |
| 54  | Chimes & Bowls Focus   | explore.focus.bells       |
...
| 262 | Wind Relax             | explore.relax.wind        |
| 300 | Cinematic Music Focus  | explore.focus.cinematic   |
+-----+------------------------+---------------------------+
$
$ rm ~/.brainfm/cache/*
$
$ brain ls
+Available Stations------------+---------------------------+
| id  | name                   | canonical                 |
+-----+------------------------+---------------------------+
| 34  | Relaxed Focus          | explore.relaxed           |
| 53  | Beach Focus            | explore.focus.beach       |
| 54  | Chimes & Bowls Focus   | explore.focus.bells       |
...
| 262 | Wind Relax             | explore.relax.wind        |
| 300 | Cinematic Music Focus  | explore.focus.cinematic   |
+-----+------------------------+---------------------------+
```

This is the code that `brain ls` runs through (skipping all the cache stuff).  Can you save this to `brain-11.py` and test it with `python brain-11.py` please?

```
import brainfm
import json
import pathlib

CONFIG_PATH = pathlib.Path("~/.brainfm/config").expanduser()
with CONFIG_PATH.open() as config_file:
    config = json.load(config_file)

client = brainfm.Connection(config["email"], config["password"])

stations = client.get_stations()
print(json.dumps(stations, indent=4, sort_keys=True))
```

The output shouldn't be too important, but if it works I had 170 lines (from `python brain-11.py | wc -l`).  Maybe a difference there will point us in a direction.

**Comment by zmre** [comment]
Yup, that snippet worked great.  But the installed `brain` still gives the 404.  The `brain` file I have installed looks like this:

``` python
#!/usr/local/opt/python3/bin/python3.6

# -*- coding: utf-8 -*-
import re
import sys

from brainfm.main.cli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

Looking at `cli/main.py`, essentially it's doing the same thing with a bunch of extra cache stuff thrown in.  The full error is this:

```
% brain ls
Traceback (most recent call last):
  File "/usr/local/bin/brain", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/brainfm/main/cli.py", line 64, in ls
    cached["stations"] = client.get_stations()
  File "/usr/local/lib/python3.6/site-packages/brainfm/__init__.py", line 155, in operation
    raise error
  File "/usr/local/lib/python3.6/site-packages/brainfm/__init__.py", line 150, in operation
    resp = self._rtecm(spec, wire_kwargs)
  File "/usr/local/lib/python3.6/site-packages/brainfm/__init__.py", line 84, in _rtecm
    "cst": self.svu + self.operation_keys[spec["name"]],
  File "/usr/local/lib/python3.6/site-packages/brainfm/__init__.py", line 60, in operation_keys
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.brain.fm/post/rtecmg
```

Looking at the cache directory, there's a single file (`svu`) and it is empty.

Huh.  I deleted the `~/.brainfm/cache` directory and reran `brain ls` and it worked fine.  So my problem is solved, but apparently having that empty `svu` file in the cache directory put things in the bad place.

**Comment by numberoverzero** [comment]
After some testing, there's a number of issues with the cache layer.  if the files are malformed in any way (esp. blank/invalid json) it just crashes and burns.  I'll get a fix up.

**Comment by numberoverzero** [comment]
Thanks again for the report and helping debug!  0.2.2 is now out.

This is a perfect candidate for adding automated tests instead of smoke testing, but I'm not personally interested in adding them right now.  For any future readers, pull requests are more than welcome.  [Testing click applications](http://click.pocoo.org/5/testing/) looks surprisingly comfortable.

**Comment by zmre** [comment]
Thanks!
