### ISSUE TITLE
API changes broke lib

### ISSUE THREAD

**Issue by zmre** [numberoverzero/brainfm#12]
I wish I had time to help fix this right now, but this has stopped working. Here are things I've identified:

* The passed in credentials now needs a field called `password` instead of `pass`
* It may also need a field `"type": "LOGIN"` (it works with it, haven't tested without)
* The `/post/rtecm` endpoint seems to be gone
* The hostname needs to be `www1.brain.fm` instead of `www.brain.fm`
* The svu stuff might not be needed, but regardless, on login, the only thing that looks similar is `r.json()["user"]["id"]`
* Fetching stations is now `GET` to `https://www1.brain.fm/stations`
* Fetching a token is now a `POST` to `https://www1.brain.fm/tokens` with JSON like, `{"stationId":35}`

Likely more things need to be updated, but that's what I had time to investigate.

**Comment by numberoverzero** [comment]
Thanks for opening the issue, and especially for including all these details.

I'm going to start digging into the necessary calls and I'll try to leave info in here.  I expect this will be a large refactor or potentially rewrite.  Given my schedule I wouldn't plan on a quick fix.

**Comment by zmre** [comment]
Understood. Thanks for looking into it.

**Comment by numberoverzero** [comment]
This one's been open too long, sorry about that.

There's a working branch at 1be2a581a1b4bcd8e309eb440049e2f47c22e4c8 which provides `get_stations`, `get_token`, and `build_stream_url`.  
Client commands are `sid`, `ls`, `gt`, `url`, and `play`.

**Comment by numberoverzero** [comment]
There's a lot more stations in `brain ls` but it's quite nice combined with grep:

```
$ brain ls | grep explore.focus
| 48  | Explore Focus          | explore.focus                              |
| 53  | Beach Focus            | explore.focus.beach                        |
| 54  | Chimes & Bowls Focus   | explore.focus.bells                        |
| 55  | Electronic Music Focus | explore.focus.electronic                   |
| 56  | Forest Focus           | explore.focus.forrest                      |
| 57  | Nightsounds Focus      | explore.focus.nightsounds                  |
| 58  | Rain Focus             | explore.focus.rain                         |
| 59  | Thunder Focus          | explore.focus.thunder                      |
| 60  | Wind Focus             | explore.focus.wind                         |
| 61  | Underwater Focus       | explore.focus.underwater                   |
| 300 | Cinematic Music Focus  | explore.focus.cinematic                    |
| 302 | Piano Focus            | explore.focus.piano                        |
| 536 | Grooves Focus          | explore.focus.grooves                      |
```

Today, sort order is on `id` but this leaves random channels intermixed; another option is to sort by `string_id` which uses some notion of namespaces (despite the existence of 253 "relax.justrelax" and 535 "focus.intense")

**Comment by numberoverzero** [comment]
Another small update: the cli now uses an environment variable `BRAINFM_SID` instead of a credentials file.  There's a new command to help generate one:

```
$ brain init
Email: user@gdomain.com
Password: <hidden>
Repeat for confirmation: <hidden>

Add the following to your .profile, .bashrc, or equivalent:

    export BRAINFM_SID="s%3...s0xo"
```

And then remember to source your bashrc/profile.
